name=$1
mkdir -v -p /vmfs/volumes/5fd9bc8d-eae87edf-e796-a0481cb8188c/$name/WinCP
cp -R -f /vmfs/volumes/5fd9bc8d-eae87edf-e796-a0481cb8188c/Default/WinCP/* /vmfs/volumes/5fd9bc8d-eae87edf-e796-a0481cb8188c/$name/WinCP

txt='
.encoding = "windows-1252"
 
config.version = "8"  
virtualHW.version = "13"  
mks.enable3d = "TRUE"  
vmci0.present = "TRUE"  
powerType.powerOn = "soft"
powerType.suspend = "soft"
guestOS = "windows9-64"
tools.syncTime = "FALSE"
sound.autoDetect = "TRUE"
sound.virtualDev = "hdaudio"
sound.fileName = "-1"
sound.present = "TRUE"
memsize = "4096"
sata0.present = "TRUE"
sata0:1.deviceType = "atapi-cdrom"
sata0:1.present = "TRUE"
usb.present = "TRUE"
ehci.present = "TRUE"
usb_xhci.present = "TRUE"
svga.graphicsMemoryKB = "1048576"
ethernet0.addressType = "generated"
ethernet0.virtualDev = "e1000e"
serial0.fileType = "thinprint"
ethernet0.present = "TRUE"
serial0.present = "TRUE"
extendedConfigFile = "WinCP.vmxf"
floppy0.present = "FALSE"
svga.vramSize = "134217728"
cleanShutdown = "FALSE"
tools.upgrade.policy = "manual"
sata0:1.startConnected = "FALSE"
sata0:1.fileName = ""
sched.cpu.units = "mhz"
sched.cpu.affinity = "all"
ethernet0.networkName = "VM Network"
toolScripts.afterPowerOn = "TRUE"
toolScripts.afterResume = "TRUE"
toolScripts.beforeSuspend = "TRUE"
toolScripts.beforePowerOff = "TRUE"
sched.cpu.min = "0"
sched.cpu.shares = "normal"
sched.mem.min = "0"
sched.mem.minSize = "0"
sched.mem.shares = "normal"



ide1:0.fileName = "WinCP.vmdk"
ide1:0.present = "TRUE"
ide1:0.redo = ""
sched.ide1:0.shares = "normal"
sched.ide1:0.throughputCap = "off"
sched.cpu.latencySensitivity = "normal"
sata0:1.autodetect = "TRUE"
tools.guest.desktop.autolock = "FALSE"
pciBridge0.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
hpet0.present = "TRUE"
nvram = "WinCP.nvram"
virtualHW.productCompatibility = "hosted"
usb.vbluetooth.startConnected = "TRUE"
firmware = "efi"
sensor.location = "pass-through"
mem.hotadd = "TRUE"
numa.autosize.cookie = "10001"
numa.autosize.vcpu.maxPerVirtualNode = "1"
pciBridge0.pciSlotNumber = "17"
pciBridge4.pciSlotNumber = "21"
pciBridge5.pciSlotNumber = "22"
pciBridge6.pciSlotNumber = "23"
pciBridge7.pciSlotNumber = "24"
usb.pciSlotNumber = "32"
ethernet0.pciSlotNumber = "160"
sound.pciSlotNumber = "33"
ehci.pciSlotNumber = "34"
usb_xhci.pciSlotNumber = "192"
vmci0.pciSlotNumber = "35"
sata0.pciSlotNumber = "36"
vmotion.checkpointFBSize = "4194304"
vmotion.checkpointSVGAPrimarySize = "134217728"
ethernet0.generatedAddressOffset = "0"
monitor.phys_bits_used = "43"
softPowerOff = "FALSE"
toolsInstallManager.lastInstallError = "0"
svga.guestBackedPrimaryAware = "TRUE"
tools.remindInstall = "FALSE"
toolsInstallManager.updateCounter = "1"
unity.wasCapable = "TRUE"
migrate.hostlog = "./WinCP-58adee60.hlog"

'


echo "$txt" > /vmfs/volumes/5fd9bc8d-eae87edf-e796-a0481cb8188c/$name/WinCP/WinCP.vmx
echo displayName = \"$name\" >> /vmfs/volumes/5fd9bc8d-eae87edf-e796-a0481cb8188c/$name/WinCP/WinCP.vmx
echo sched.swap.derivedName = "/vmfs/volumes/5fd9bc8d-eae87edf-e796-a0481cb8188c/$name/WinCP/WinCP-04f4ccf5.vswp" >> /vmfs/volumes/5fd9bc8d-eae87edf-e796-a0481cb8188c/$name/WinCP/WinCP.vmx
vim-cmd solo/registervm /vmfs/volumes/5fd9bc8d-eae87edf-e796-a0481cb8188c/$name/WinCP/WinCP.vmx
